import React, { useState } from 'react';

function Dashboard() {
  const [prompt, setPrompt] = useState("");

  const dashboardStyle = {
    display: 'grid', gridTemplateColumns: '1fr 1fr', gridTemplateRows: '1fr 1fr', gap: '20px',
    width: '95vw', height: '90vh', maxWidth: '1400px'
  };

  const cardBase = {
    backgroundColor: 'rgba(255,255,255,0.85)', backdropFilter: 'blur(12px)',
    borderRadius: '30px', padding: '30px', boxShadow: '0 10px 30px rgba(0,0,0,0.05)',
    display: 'flex', flexDirection: 'column'
  };

  return (
    <div style={dashboardStyle}>
      
      {/* 1. LEFT SIDE: CHAT UI */}
      <div style={{ ...cardBase, gridRow: '1 / span 2' }}>
        <h3 style={{ color: '#6b705c', marginTop: 0 }}>Messages 💬</h3>
        <div style={{ flex: 1, background: '#faf9f6', borderRadius: '20px', marginBottom: '15px', padding: '15px' }}>
          <div style={{ marginBottom: '10px' }}>
            <span style={{ fontWeight: 'bold', color: '#888' }}>Mentor:</span> Hi! Welcome to the platform.
          </div>
          <div style={{ textAlign: 'right' }}>
            <span style={{ background: '#b5ead7', padding: '8px 15px', borderRadius: '15px' }}>Thanks! Excited to be here.</span>
          </div>
        </div>
        <div style={{ display: 'flex', gap: '10px' }}>
          <input placeholder="Type a message..." style={{ flex: 1 }} />
          <button style={{ background: '#b8e1ff', color: '#444' }}>Send</button>
        </div>
      </div>

      {/* 2. TOP RIGHT: CALENDAR */}
      <div style={{ ...cardBase }}>
        <h3 style={{ color: '#6b705c', marginTop: 0 }}>Calendar 📅</h3>
        <div style={{ flex: 1, display: 'grid', gridTemplateColumns: 'repeat(7, 1fr)', gap: '5px', textAlign: 'center', fontSize: '0.8rem' }}>
          {['S','M','T','W','T','F','S'].map(d => <div key={d} style={{fontWeight:'bold'}}>{d}</div>)}
          {[...Array(30)].map((_, i) => (
            <div key={i} style={{ padding: '10px', background: i === 15 ? '#ffdac1' : '#f0f0f0', borderRadius: '10px', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>{i+1}</div>
          ))}
        </div>
      </div>

      {/* 3. BOTTOM RIGHT: AI PROMPT + MATCH GENERATOR */}
      <div style={{ ...cardBase }}>
        <h3 style={{ color: '#6b705c', marginTop: 0 }}>AI Assistant 🤖</h3>
        
        <div style={{ flex: 1, display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center', textAlign: 'center' }}>
          <div style={{ fontSize: '1.3rem', fontWeight: '600', color: '#555', fontStyle: 'italic', marginBottom: '15px', lineHeight: '1.4' }}>
            "What’s something new you’d love to learn or try in the next few months? How does the idea of tackling it make you feel?"
          </div>

          <p style={{ fontSize: '0.85rem', color: '#999', marginTop: '10px', maxWidth: '90%' }}>
            * New prompt generated by AI assistant to help with thinking and reflection during mentorship session.
          </p>

          {/* TWO BUTTONS ROW */}
          <div style={{ display: 'flex', gap: '15px', width: '100%', marginTop: 'auto' }}>
            <button style={{ flex: 1, background: '#b8e1ff', color: '#444' }}>
              Generate New Match 👥
            </button>
          </div>

        </div>
      </div>

    </div>
  );
}

export default Dashboard;